# Generated by Django 3.0.2 on 2020-02-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_movie_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
