# Generated by Django 2.2 on 2020-02-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_messages_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
