# Generated by Django 3.0.2 on 2020-02-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_movie_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movielocation',
            unique_together={('movie', 'location')},
        ),
    ]
