# Generated by Django 2.2 on 2020-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200219_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='location',
            field=models.ManyToManyField(to='home.Locations'),
        ),
        migrations.DeleteModel(
            name='MovieLocation',
        ),
    ]
