# Generated by Django 3.0.2 on 2020-02-10 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200210_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielocation',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Locations'),
        ),
    ]
