# Generated by Django 3.0.2 on 2020-02-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200210_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='movielocation',
            name='movie',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=None,
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=None,
        ),
        migrations.RemoveField(
            model_name='rating',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userslocation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userslocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userslocation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieLocation',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='UsersLocation',
        ),
    ]
