# Generated by Django 3.0.2 on 2020-02-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_locations_movie_movielocation_rating_userslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
